# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 269382 Data Analytics for Non-IT
author: Kasemsit Teeyapan
logo: logo.png
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", ".venv/*"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kasemsit/269382  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  announcement: "กำลังทะยอยอัพเดท..."
  
launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab" 

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js  # for Plotly
    suppress_warnings: ["mystnb.unknown_mime_type"]
    html_theme_options: # https://sphinx-book-theme.readthedocs.io/en/latest/customize/index.html
      search_bar_text: "ค้นหาคำในเล่ม..." # https://github.com/executablebooks/jupyter-book/issues/770
      toc_title: "สารบัญ"
      show_toc_level: 2
      use_sidenotes: true  # footnote as margin note
      #announcement: "⚠️เวอร์ชันทดสอบ⚠️"   

parse:
  myst_enable_extensions:
    - amsmath    
    - colon_fence
    - deflist
    - dollarmath
    #"fieldlist",
    #"html_admonition",
    #"html_image",
    - linkify
    #"replacements",
    #"smartquotes",
    #"strikethrough",
    - substitution
    #"tasklist",  
